### ISSUE TITLE
希望能够使用拆包数据

### ISSUE THREAD

**Issue by DavidDiao** [graueneko/graueneko.github.io#11]
使用拆包数据[Perfare/ArknightsGameData](https://github.com/Perfare/ArknightsGameData)能够更方便的进行数据的批量处理，在有新东西加入的时候也能更迅速的进行反应（伪需求x）
如果#10 被采用的话，物品/干员名称使用内部编号也更不容易出现问题
~~其实是我想写 输入干员当前和目标精英状态、技能等级，直接输出所需总材料，数据量太大不得不导拆包数据~~

**Comment by gneko** [comment]
感谢建议，这是在计划之内的事项。近期可能会有次大幅重构，会以这个拆包数据为核心。

**Comment by DavidDiao** [comment]
@graueneko 那可以透露一下 是直接使用原始数据 还是经过一定预处理的数据吗
不希望自己写的东西导致风格不一致

**Comment by gneko** [comment]
直接用原始数据或者原始数据的备份（避免因为官方压力导致数据下线/迁移）

**Comment by AlvISsReimu** [comment]
支持使用拆包数据作为目前的一个统一标准。今天就碰到有朋友在做相关统计时，要从我这边自己定的物品id转换到您这边的id的情况。如果舟游相关工具这方面能够统一的话，应该能提升联合应用的流畅性。

**Comment by gneko** [comment]
已在新版工具箱aktools中实现。
