### ISSUE TITLE
关于某些计算器的方便化设计和基建模拟的建议

### ISSUE THREAD

**Issue by Evealicemier** [graueneko/graueneko.github.io#12]
纯粹个人想法 酸民只有一张嘴还有一个自制excel。
简单来说就是，事实上干员列表可以直接联动等级计算器和材料计算，举个例子，我选择六星0-2星 顺便选一下人，选一下技能专精 就知道我到底需要多少什么材料，也就知道我还缺些什么……
而对于材料计算器，事实上可以加入候选精2 勾选专精等级这些更加方便的东西……
我个人做的事情只是做了一张实现以上功能的excel而已，而且事实上不包括钱和经验的计算因为没必要做了，甚至并没有完全做完（主要工作量是数据录入，不过有原数据的话直接写个python导入excel也可以不过我用蠢办法了）……但是excel毕竟传播并不是非常方便就是了所以想在这里提一下，也希望更多讨论，毕竟我不太希望白做一张表。

其次关于之前有人提到的有关基建模拟器，以及将基建的产出的影响加入练级计算机里，我个人认为后者没有任何意义，因为我自己也试图做过，然而实际基建的波动和理论上平均化的基建的差距远比想象的大。首先玩家也不是拥有所有干员，其次，就算理论上来说，按照玩家的干员表可以计算出最优解，也不可能假设玩家打闹铃定点定班换干员。故我认为用基建模拟器去干涉其他计算机完全没有实用性。

然后是关于基建模拟器本身，我个人认为这个模拟器只需要做到——能按照玩家给定的某类状态（多少加成，是否用无人机）计算每日产出数值和等价理智即可，这里主要问题还是在于不可能假设玩家打闹铃定点定班换干员。基建本身是积累形生产设施，用存在偏差的日产出乃至周产出理论值去推算实际情况会产生很大的误差。所以我认为预期弄成动态不如完全静态化，直接给出理论产值让使用者自己斟酌。

当然我之所以那么想主要有3个原因，1.基建设计相对固定，有成熟的规划可以参考，事实上并不必频繁模拟。2.舟游限肝容易长草，玩家往往容易换人断档。3.多数人不太愿意考虑的过于细致，毕竟有大佬作业可以抄（基建规划作业），so我认为功能过于全面反而无人使用，化繁为简直接给用户看静态等价产出更好 且这样做工作量不大

ps：除此之外，这是我个人做的一个刷图产出统计计划，我不知道其他人是否有类似的想法，就是刷图材料出货统计并用这个计算材料价值（比如某干员精2，我用此方法推算得推进精2材料除芯片成本是2540理智），当然考虑过后我觉得这个功能繁琐而且意义有限，这里只是提一下希望抛砖引玉（虽然我个人是做完了这个功能的50%）

**Comment by DavidDiao** [comment]
技能等级和精英的材料我本来想写的 结果发现已经有人做了（https://ark-nights.com/ 缺点只是只能选当前状态，目标状态只能是下一阶段） 然后就没有动力了x
基建模拟器恶心的就是干员要经常换 一不小心就会断片 并不能完全模拟出结果；相比之下只需要留足余量，没有空转，一定不会亏，所以我觉得没有这个需求
计算价值。。有什么用吗。。不管价值高不高，该刷不还是得刷吗

**Comment by Evealicemier** [comment]
就这次的活动而言我觉得完整的材料表其实是有必要的…这也是为什么我做了完整版excel列表（功能比那个丰富但是可移植性为0......…不过说实在的受众可能并不广 因为大多数人不会做豚鼠 肯定是缺什么现刷
基建模拟器的话我觉得做一个静态的就好……或者我去看看怎么做吧
至于价值，这只是解决了2个一直有人问的问题：材料我要刷多久，xxx精2材料怎么那么贵啊，我说说只是抛砖引玉了 个人算下来事实上没什么实用意义

**Comment by gneko** [comment]
内容比较长我总结一下吧：
1. 干员表整合材料/升级计算器，加入升级/专精技能需要的材料：这个想法非常好，我之前没有想到，可以加入开发计划中；
2. 基建模拟器：说真的我并不看好基建模拟器，原因跟你说的差不多在于收益低且不稳定，如果按照无加成的最低收益来计算又会有很大误差。而且基建要考虑长期收益，目前会精二角色的人大部分都是会碎体力的，用不到这个。尽管如此，这也在开发计划中（但优先级很低）。
3. 刷图收益：有人在做相关统计和内容：[https://penguin-stats.io/intro](https://penguin-stats.io/intro) 如果有类似想法可以考虑一起维护。
总之，目前短期目标是加入[1]。由于现在正在向Angular JS迁移（考虑到可维护性和潜在的开发者），这可能需要一段时间。
感谢你的建议。
