### ISSUE TITLE
希望升级消耗计算器能增加考虑基建的情况

### ISSUE THREAD

**Issue by ichxxx** [graueneko/graueneko.github.io#2]
因为基建每日的金币收入也十分可观，希望能在升级消耗计算器中考虑进去。

假设玩家能完成基建中贸易站每日的所有订单，根据玩家拥有几个不同等级的贸易站以及常驻干员的效率加成进行相应的计算。

因为每个订单消耗的赤金数量是随机的（2-4个）（还是根据贸易站等级有相应的概率？这个不太了解），不能精确计算出每天可以获得的金币数量，所以可以考虑最好和最差两种情况，给出一个范围或者其他更好的解决办法。

一点拙见。

**Comment by ichxxx** [comment]
噢噢，还有建造站中的经验书，这个忘记说了..

**Comment by gneko** [comment]
基建的书产量太低，对结果的影响不大，而且需要强化的时候一般也不会等基建，这是我没考虑这部分的原因。

**Comment by ichxxx** [comment]
好的~
