### ISSUE TITLE
about score calculation

### ISSUE THREAD

**Issue by Faryzal2020** [graueneko/graueneko.github.io#3]
how do you do the score calculation? i noticed that the tag_count in here is always zero, which results the avg_char_tag being always infinity, but regardless it still showing the correct numbers in the website. how?
![image](https://user-images.githubusercontent.com/8612170/57252967-832ae380-7088-11e9-8f2e-9e86d52b7610.png)

**Comment by gneko** [comment]
That's actually a bug, `avg_char_tag`  is infinite, and in the score calculation, `num/avg_char_tag` always equals to zero so that the result is incorrect but seems not affected.

I wondered why the result is not what i expected, but didn't notice that, now i know.

Fixed, thanks.
