### ISSUE TITLE
希望增加基建模拟建造和干员数据对比的功能

### ISSUE THREAD

**Issue by EBlaster** [graueneko/graueneko.github.io#4]
可能实现起来有些复杂，不过很实用

**Comment by gneko** [comment]
这功能需要大量数据和比较复杂的实现，目前还没想好怎么做，有计划。

**Comment by gneko** [comment]
https://somedata.top/Arknights/ 已有人实现类似功能，这部分暂时推后。如果实现的话会尽量避免重复造轮子，加入其它新功能。

**Comment by gneko** [comment]
上面链接已经比较完善且不断更新，因此这部分功能暂不考虑。
