### ISSUE TITLE
希望增加模拟十连功能

### ISSUE THREAD

**Issue by 11zi** [graueneko/graueneko.github.io#6]
让微氪玩家舒服舒服! 
或者在招募计算里加一个模拟招募, 权重的意思有点不明白

**Comment by gneko** [comment]
模拟十连有计划，但可能不会很快实现，现在可以尝试别人做的 [明日方舟寻访模拟器 v1.0](https://bbs.nga.cn/read.php?tid=17219048)。

权重是一种大体上的tag排序，综合以下几点考虑：
1. 平均星级高>平均星级低
2. TAG数量少>TAG数量多（消耗低）
3. 组合内角色数量少>角色数量多（更精准）

这是目前的排序方式，权重仍在调整中，但整体思路不变。

**Comment by 11zi** [comment]
> 权重是一种大体上的tag排序，综合以下几点考虑：
> 1. 平均星级高>平均星级低
> 2. TAG数量少>TAG数量多（消耗低）
> 3. 组合内角色数量少>角色数量多（更精准）
> 
> 这是目前的排序方式，权重仍在调整中，但整体思路不变。

那模拟公开招募怎么样...
芙蓉炎熔克洛斯实在是太多了:cry:

**Comment by ZPagylWM** [comment]
我写了一个简单的模拟抽卡的，统计抽10000次，抽出6星是第几次，用频率来模拟概率的。

```
def calcF(times=100000):
    tl = []
    for i in range(times):
        count = 0
        p = 0.02
        for j in range(1, 100):
            k = rd.randint(0, 100)
            if count > 50:
                p = round(p + 0.02, 2)
            count += 1
            if k < round(100 * p):
                break
        tl.append(count)
    c = Counter(tl)
    counts = sorted(c.items(), key=lambda item: item[0])
    x = [item[0] for item in counts]
    y = [item[1] / times for item in counts]
    plt.plot(x, y, '-')
    plt.xlabel(’n times')
    plt.ylabel('Frequency')
    plt.legend(loc=3)
    plt.title('')
    plt.show()
    plt.savefig('counts.png')
    return counts
``` 
有些粗劣，希望不要嫌弃

**Comment by ZPagylWM** [comment]
![c2](https://user-images.githubusercontent.com/32705612/57976811-03076500-7a1c-11e9-85fc-962a97e3e464.png)
这个是用频率模拟计算概率，显示【一共抽多少次能出一张6星卡】，次数的概率分布。

**Comment by gneko** [comment]
已有较多类似功能的工具，这部分实现计划推迟以避免重复造轮子。
将来可能会实现类似功能，但会优先考虑在新版工具箱上实现，如仍有需求请移步新工具箱repo另开issue。
