### ISSUE TITLE
公开招募计算器可否考虑做成横向的

### ISSUE THREAD

**Issue by Ricky816845** [graueneko/graueneko.github.io#7]
或者筛选条件放到左边浮动也行

**Comment by gneko** [comment]
是指在电脑端的横屏浏览，还是其他情况？
可能会改成以下界面：
![横向](https://user-images.githubusercontent.com/48706971/57860970-5e710180-7828-11e9-9549-4715d442286f.png)

**Comment by Ricky816845** [comment]
额对,是电脑端浏览,是这个意思..

**Comment by gneko** [comment]
已经修改并调整完成，感谢建议。

如果还有其它建议，欢迎发起新issue。
