### ISSUE TITLE
我总觉得这权重有点问题....

### ISSUE THREAD

**Issue by 11zi** [graueneko/graueneko.github.io#8]
![2019-05-24_20 54 09](https://user-images.githubusercontent.com/28333452/58329035-2f7d1000-7e66-11e9-89fa-5eba77623e9d.jpg)

**Comment by gneko** [comment]
这整体上是符合我自己的预期的。如果感觉哪里不适合，请描述一下？

**Comment by 11zi** [comment]
就是它明明必定出4星, 另一个明显就只有3星,4星和5星基本不可能出...
我觉得必定出四星的标签的权重被预估的太低了....

**Comment by gneko** [comment]
了解，已调整了相关算法，感谢反馈。
